kind: Cluster
apiVersion: kind.sigs.k8s.io/v1alpha3
kubeadmConfigPatches:
  - |
    apiVersion: kubeadm.k8s.io/v1beta2
    kind: ClusterConfiguration
    metadata:
      name: config
    apiServer:
      extraArgs:
        "feature-gates": "VolumeSnapshotDataSource=true"
    scheduler:
      extraArgs:
        "feature-gates": "VolumeSnapshotDataSource=true"
    controllerManager:
      extraArgs:
        "feature-gates": "VolumeSnapshotDataSource=true"
  - |
    apiVersion: kubeadm.k8s.io/v1beta2
    kind: InitConfiguration
    metadata:
      name: config
    nodeRegistration:
      kubeletExtraArgs:
        "feature-gates": "VolumeSnapshotDataSource=true"
nodes:
# the control plane node
- role: control-plane
  extraMounts:
    - containerPath: /opt/local-path-provisioner
      hostPath: /mnt
      readOnly: false
- role: worker
  extraMounts:
    - containerPath: /opt/local-path-provisioner
      hostPath: /mnt
      readOnly: false
- role: worker
  extraMounts:
    - containerPath: /opt/local-path-provisioner
      hostPath: /mnt
      readOnly: false
